#https://docs.github.com/de/rest/releases/releases?apiVersion=2022-11-28#list-releases
name: Manual release PR
on:
  workflow_dispatch

jobs:
  draftInformation:
    name: Get Draft
    runs-on: ubuntu-latest
    outputs:
      draft_version: ${{ steps.properties.outputs.draft_version }}
      draft_changelog: ${{ steps.properties.outputs.draft_changelog }}
    steps:

      - name: Export Properties
        id: properties
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        shell: bash
        run: |
          DRAFT_VERSION="$(gh api repos/{owner}/{repo}/releases \
          --jq '.[] | select(.draft == true) | .tag_name' \
          | cut -c 2-6 )"
          
          DRAFT_CHANGELOG="$(gh api repos/{owner}/{repo}/releases \
          --jq '.[] | select(.draft == true) | .body')"
          
          echo "draft_version=$DRAFT_VERSION" >> $GITHUB_OUTPUT
          echo "draft_changelog=$DRAFT_CHANGELOG" >> $GITHUB_OUTPUT
    
  createPR:
    name: Create PR
    runs-on: ubuntu-latest
    needs: [draftInformation]
    permissions:
      contents: write
      pull-requests: write
    steps:
      # Check out current repository
      - name: Fetch Sources
        uses: actions/checkout@v4

      # Set up Java environment for the next steps
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: zulu
          java-version: 17

      # Setup Gradle
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
        with:
          gradle-home-cache-cleanup: true

      - name: Patch Version
        if: ${{ needs.draftInformation.outputs.draft_version != '' }}
        env:
          VERSION: ${{ needs.draftInformation.outputs.draft_version }}
        run: ./gradlew newVersion -PnewVersion="$VERSION"

      - name: Patch Changelog
        if: ${{ needs.draftInformation.outputs.draft_changelog != '' }}
        env:
          CHANGELOG = ${{ needs.draftInformation.outputs.draft_changelog }}
        run: ./gradlew patchChangelog --release-note="$CHANGELOG" -PrepositoryUrl="${{ github.server_url }}/${{ github.repository }}

      - name: Build plugin
        run: ./gradlew build

      # Create a pull request
      - name: Create Pull Request
        if: ${{ needs.draftInformation.outputs.draft_changelog != '' && needs.draftInformation.outputs.draft_version != '' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VERSION: ${{ needs.draftInformation.outputs.draft_version }}
        run: |
          BRANCH="release-$VERSION"
          LABEL="release"

          git config user.email "action@github.com"
          git config user.name "GitHub Action"

          git checkout -b $BRANCH
          git commit -am "Release $VERSION"
          git push --set-upstream origin $BRANCH
          
          gh label create "$LABEL" \
            --description "Pull requests with new release version and changelog" \
            --force \
            || true

          gh pr create \
            --title "Release - \`$VERSION\`" \
            --body "Current pull request contains patched \`CHANGELOG.md\` file for the \`$VERSION\` version." \
            --label "$LABEL" \
            --head $BRANCH