# https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#workflow_dispatch
name: Release PR
on:
  release:
    types: [prereleased]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Runs on Pre-Release
        if: 'github.event.prerelease'
        run: echo "This is a Pre-Release"
      - name: Runs on Release
        if: '!github.event.prerelease'
        run: echo "This is a Release"