# https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#workflow_dispatch
name: Create Release with Asset
on:
  workflow_run:
    workflows: [ Build ]
    types: [ completed ]

# Run when a release commit is successfully built in the main branch
jobs:
  on-success:
    runs-on: ubuntu-latest
    if: "startsWith('${{ github.event.workflow_run.head_commit.message }}', 'Release v')"
    permissions:
      contents: write
    steps:

      # Check out repository
      - name: Fetch Sources
        uses: actions/checkout@v4

      # Java Env
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: zulu
          java-version: 17

      # Setup Gradle
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
        with:
          gradle-home-cache-cleanup: true

      # Get Release Tag from Draft
      - name: Export properties
        id: properties
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        shell: bash
        run: |
          RELEASE_TAG="$(gh api repos/{owner}/{repo}/releases \
          --jq '.[] | select(.draft == true) | .tag_name' )"
          
          echo "release_tag=$RELEASE_TAG" >> $GITHUB_OUTPUT

      # Release current draft release
      - name: Release Draft
        if: steps.properties.outputs.release_tag == github.event.workflow_run.head_commit.tag
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        shell: bash
        run: |
          gh release edit ${{ github.event.workflow_run.head_commit.tag }} \
            --draft=false \
            --latest \
            --verify-tag

      # Build artifact (adjust to required action, e.g. buildPlugin, jar, war, ...)
      - name: Build
        run: ./gradlew war

      # Upload build artifact as a release asset
      - name: Upload release Asset
        if: steps.properties.outputs.release_tag == github.event.workflow_run.head_commit.tag
        env:
          GIHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh release upload ${{ steps.properties.outputs.release_tag }} ./build/libs/*